"""mymcp — MCP server for Linux system control."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("mymcp")
except PackageNotFoundError:
    try:
        from mymcp._version import __version__  # generated by setuptools-scm
    except ImportError:
        __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
