FROM rockylinux:9

RUN dnf install -y epel-release && \
    dnf install -y \
        python3.11 python3.11-pip \
        git curl rsync systemd \
        procps-ng ripgrep bats openssl && \
    dnf clean all

STOPSIGNAL SIGRTMIN+3
ENV container=docker

WORKDIR /src
