package setup

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

func defaultOptions() Options {
	return Options{
		Bind: "0.0.0.0", Port: 8765, ServiceUser: "root",
		ConfigDir: "/etc/mymcp", LogDir: "/var/log/mymcp",
		RecorderDataDir: "/var/lib/mymcp/recorder",
		Audit:           true, ClientName: "default", ClientRole: "rw", Start: true,
	}
}

func TestPlanFromOptionsGeneratesMetricsTokenByDefault(t *testing.T) {
	pf := Preflight{IsRoot: true, HasSystemd: true}
	p, err := PlanFromOptions(defaultOptions(), pf, newFakeSystem())
	if err != nil {
		t.Fatal(err)
	}
	if p.MetricsToken == "" {
		t.Fatal("a metrics token must be generated by default")
	}
	if !p.HasSystemd {
		t.Fatal("HasSystemd must be carried from preflight into the Plan")
	}
}

func TestPlanFromOptionsRefusesRecorderWhenUnavailable(t *testing.T) {
	o := defaultOptions()
	o.Recorder = true
	pf := Preflight{IsRoot: true, HasSystemd: true, Recorder: RecorderUnavailable}
	if _, err := PlanFromOptions(o, pf, newFakeSystem()); err == nil {
		t.Fatal("-recorder with no pipx and no mymcp-recorder must be a clear error, not a late failure")
	}
}

func TestPlanFromOptionsSetsNeedsInjectOnlyForPipxPath(t *testing.T) {
	o := defaultOptions()
	o.Recorder = true
	o.RecorderAPIKey = "sk-test"
	viaPipx, err := PlanFromOptions(o, Preflight{IsRoot: true, HasSystemd: true, Recorder: RecorderViaPipx}, newFakeSystem())
	if err != nil {
		t.Fatal(err)
	}
	if !viaPipx.Recorder.NeedsInject {
		t.Error("pipx path must request an inject")
	}
	ready, err := PlanFromOptions(o, Preflight{IsRoot: true, HasSystemd: true, Recorder: RecorderReady}, newFakeSystem())
	if err != nil {
		t.Fatal(err)
	}
	if ready.Recorder.NeedsInject {
		t.Error("already-installed recorder must not re-inject")
	}
}

func TestWizardSeedsDefaultsFromExistingEnv(t *testing.T) {
	pf := Preflight{
		IsRoot: true, HasSystemd: true,
		ExistingEnv: "MYMCP_PORT=9000\nMYMCP_HOST=127.0.0.1\n",
	}
	// All answers blank -> every default is accepted.
	in := strings.NewReader(strings.Repeat("\n", 20))
	pr := NewPrompter(in, &bytes.Buffer{}, newFakeSystem())
	p, err := PlanFromWizard(defaultOptions(), pf, pr, newFakeSystem())
	if err != nil {
		t.Fatal(err)
	}
	if p.Port != 9000 || p.Bind != "127.0.0.1" {
		t.Fatalf("update mode must seed from the existing .env, got %s:%d", p.Bind, p.Port)
	}
}

func TestExposureWarningWildcardOnly(t *testing.T) {
	if ExposureWarning("0.0.0.0") == "" {
		t.Error("binding 0.0.0.0 must warn: a reachable port plus a token is a root shell")
	}
	if ExposureWarning("127.0.0.1") != "" {
		t.Error("loopback bind needs no exposure warning")
	}
}

func TestFirewallHintMatchesDetectedFirewall(t *testing.T) {
	ufw := newFakeSystem()
	ufw.Paths["ufw"] = "/usr/sbin/ufw"
	if got := FirewallHint(ufw, 8765); !strings.Contains(got, "ufw allow 8765") {
		t.Errorf("ufw hint = %q", got)
	}
	fw := newFakeSystem()
	fw.Paths["firewall-cmd"] = "/usr/bin/firewall-cmd"
	if got := FirewallHint(fw, 8765); !strings.Contains(got, "firewall-cmd") {
		t.Errorf("firewalld hint = %q", got)
	}
	if got := FirewallHint(newFakeSystem(), 8765); got != "" {
		t.Errorf("no firewall detected should give no hint, got %q", got)
	}
}

func TestPortInUseParsesSs(t *testing.T) {
	sys := newFakeSystem()
	sys.Outputs["ss -tlnH"] = "LISTEN 0 4096 0.0.0.0:8765 0.0.0.0:*\n"
	if !PortInUse(sys, "0.0.0.0", 8765) {
		t.Error("occupied port not detected")
	}
	if PortInUse(sys, "0.0.0.0", 9999) {
		t.Error("free port reported busy")
	}
}

func TestWizardDoesNotSpinOnAnExhaustedReader(t *testing.T) {
	// Ask returns its default instantly once the reader is exhausted; an
	// unbounded validation loop would spin forever.
	pf := Preflight{IsRoot: true, HasSystemd: true}
	pr := NewPrompter(strings.NewReader(""), &bytes.Buffer{}, newFakeSystem())
	done := make(chan struct{})
	go func() {
		defer close(done)
		if _, err := PlanFromWizard(defaultOptions(), pf, pr, newFakeSystem()); err == nil {
			t.Error("an exhausted reader must be an error, not a silent all-defaults plan")
		}
	}()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("PlanFromWizard did not terminate on an exhausted reader")
	}
}

func TestWizardAcceptsAValidPortOnTheLastAllowedAttempt(t *testing.T) {
	// Four bad answers then a good one must be accepted, not discarded by the cap.
	pf := Preflight{IsRoot: true, HasSystemd: true}
	in := strings.NewReader("\n" + "bad\nbad\nbad\nbad\n9001\n" + strings.Repeat("\n", 20))
	pr := NewPrompter(in, &bytes.Buffer{}, newFakeSystem())
	p, err := PlanFromWizard(defaultOptions(), pf, pr, newFakeSystem())
	if err != nil {
		t.Fatalf("a valid answer within the cap must be accepted: %v", err)
	}
	if p.Port != 9001 {
		t.Fatalf("Port = %d, want 9001", p.Port)
	}
}

func TestPortInUseDistinguishesConcreteBinds(t *testing.T) {
	sys := newFakeSystem()
	sys.Outputs["ss -tlnH"] = "LISTEN 0 4096 127.0.0.1:8765 0.0.0.0:*\n"
	if PortInUse(sys, "10.0.0.5", 8765) {
		t.Error("127.0.0.1:8765 does not conflict with binding 10.0.0.5:8765")
	}
	if !PortInUse(sys, "127.0.0.1", 8765) {
		t.Error("same concrete address must conflict")
	}
	if !PortInUse(sys, "0.0.0.0", 8765) {
		t.Error("a wildcard bind conflicts with any listener on that port")
	}
	wild := newFakeSystem()
	wild.Outputs["ss -tlnH"] = "LISTEN 0 4096 0.0.0.0:8765 0.0.0.0:*\n"
	if !PortInUse(wild, "10.0.0.5", 8765) {
		t.Error("a wildcard listener conflicts with any bind on that port")
	}
}

func TestPlanFromOptionsSeedsFromExistingEnvOnTheYesPath(t *testing.T) {
	// Automation uses -yes; a re-run there must not mint a new metrics token
	// or silently turn the recorder off.
	pf := Preflight{
		IsRoot: true, HasSystemd: true, Recorder: RecorderReady,
		ExistingEnv: "MYMCP_PORT=9000\nMYMCP_METRICS_TOKEN=tok_metrics_old\n" +
			"MYMCP_AUDIT_ENABLED=false\nMYMCP_RECORDER_ENABLED=true\n" +
			"MYMCP_RECORDER_LLM_PROVIDER=openai\n",
	}
	p, err := PlanFromOptions(defaultOptions(), pf, newFakeSystem())
	if err != nil {
		t.Fatal(err)
	}
	if p.Port != 9000 {
		t.Errorf("Port = %d, want 9000", p.Port)
	}
	if p.MetricsToken != "tok_metrics_old" {
		t.Errorf("MetricsToken = %q — a re-run must not rotate it and break Prometheus", p.MetricsToken)
	}
	if p.AuditEnabled {
		t.Error("AuditEnabled must be seeded from the host's actual setting")
	}
	if !p.Recorder.Enabled || p.Recorder.Provider != "openai" {
		t.Errorf("recorder settings not preserved: %+v", p.Recorder)
	}
}

func TestSeedingNeverOverridesAnExplicitlyTypedFlag(t *testing.T) {
	pf := Preflight{IsRoot: true, HasSystemd: true, ExistingEnv: "MYMCP_PORT=9000\n"}
	o := defaultOptions()
	o.Port = 7777
	o.Explicit = map[string]bool{"port": true}
	p, err := PlanFromOptions(o, pf, newFakeSystem())
	if err != nil {
		t.Fatal(err)
	}
	if p.Port != 7777 {
		t.Fatalf("Port = %d, want the typed 7777 to win over the seeded 9000", p.Port)
	}
}

func TestSeedingKeepsAnIntentionallyEmptyMetricsToken(t *testing.T) {
	pf := Preflight{IsRoot: true, HasSystemd: true, ExistingEnv: "MYMCP_METRICS_TOKEN=\n"}
	p, err := PlanFromOptions(defaultOptions(), pf, newFakeSystem())
	if err != nil {
		t.Fatal(err)
	}
	if p.MetricsToken != "" {
		t.Fatalf("MetricsToken = %q — an explicitly empty value means /metrics is deliberately unauthenticated", p.MetricsToken)
	}
}
